OMOP CDM bug fixes for MU + GPC

diff --git a/OMOP_ON_PCORNET_CDM/Makefile b/OMOP_ON_PCORNET_CDM/Makefile
--- a/OMOP_ON_PCORNET_CDM/Makefile
+++ b/OMOP_ON_PCORNET_CDM/Makefile
@@ -2,7 +2,7 @@
 AIRFLOW_UID := $(shell id -u)
 
 # Download docker-compose.yaml if it doesn't exist
-build:
+airflow-omop-build:
 	@echo "Checking for docker-compose.yaml..."
 	@if [ ! -f docker-compose.yaml ]; then \
 		echo "Downloading docker-compose.yaml..."; \
@@ -14,13 +14,33 @@ build:
 	docker compose up airflow-init --build
 
 # Start all Airflow services
-deploy:
+airflow-omop-deploy:
 	docker compose up -d
 
-stop:
+airflow-omop-connections:
+	@echo "Creating datasource connections..."
+	docker compose exec airflow-apiserver bash -c '\
+		set -euo pipefail; \
+		BASE_DIR="/opt/airflow/env"; \
+		echo "=== Installing Airflow connections (Snowflake) ==="; \
+		for acct_dir in "$$BASE_DIR"/*/; do \
+			acct="$$(basename "$$acct_dir")"; \
+			script="$$acct_dir/connections.sh"; \
+			if [ -f "$$script" ]; then \
+				echo ""; \
+				echo ">>> Running connection script for account: $$acct"; \
+				bash "$$script"; \
+			else \
+				echo "!!! Skipping $$acct (connections.sh not found)"; \
+			fi; \
+		done; \
+		echo ""; \
+		echo "✅ Done installing all connections." \
+	'
+airflow-omop-stop:
 	docker compose down
 
-clean:
+airflow-omop-clean:
 	docker compose down --volumes --rmi all
 
 # Launch Jupyter Lab
